server:
  port: 8888

spring:
  application:
    name: configserver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sundalei/greeting-config